apiVersion: veecode.backstage.io/v1alpha1
kind: Cluster
metadata:
  name: "aws-k8s-ec2-teste"
  environment:
    cluster_type: ec2
    domain: vkpr.platform.vee.codes
    public_ip: 100.28.100.105
  annotations:
    github.com/project-slug: veecode-homolog/aws-k8s-ec2-teste
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: terraform-deploy.yml,start-instance.yml,stop-instance.yml,terraform-destroy.yml,deploy-dashboard
    cluster/instructions: "# Run the following commands to import the kubeconfig:\n  ssh -i ./cert.pem -o StrictHostKeyChecking=no $USERNAME@$100.28.100.105 \"mkdir -p .kube && k3d kubeconfig get k3s > ~/.kube/config\"\n  scp -i ./cert.pem $USERNAME@$100.28.100.105:~/.kube/config ~/.kube/config-aws-k8s-ec2-teste\n  yq -e 'del(.clusters[0].cluster.certificate-authority-data) | .clusters[0].cluster.insecure-skip-tls-verify=true | .clusters[].cluster.server |= sub(\"0.0.0.0\", \"100.28.100.105\")' -i ~/.kube/config-aws-k8s-ec2-teste\n  export KUBECONFIG=~/.kube/config-aws-k8s-ec2-teste\n  kubectl get pods -A\n"
spec:
  type: ec2
  lifecycle: experimental
  owner: "group:default/admin"
  environment: 'environment:default/platform_homolog_environment'
