name: Secret

on:
  workflow_dispatch:
env:
  PORT: 6550
  USERNAME: ec2-user
jobs:
  Secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: artifacts
        run: |
          echo "${{ secrets.KEYPAIR }}" > cert.pem
          chmod 600 cert.pem

      - name: Upload cert.pem
        uses: actions/upload-artifact@v3
        with:
          name: cert.pem
          path: ./cert.pem

      - name: echo_secret
        run: |
          echo "API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
                AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
                AWS_HOSTED_ZONE_ID: ${{ secrets.AWS_HOSTED_ZONE_ID }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
                AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
                DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
                DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                EMAIL_GITHUB: ${{ secrets.EMAIL_GITHUB }}
                GH_EMAIL: ${{ secrets.GH_EMAIL }}
                GH_USERNAME: ${{ secrets.GH_USERNAME }}
                GRAFANA_API_TOKEN: ${{ secrets.GRAFANA_API_TOKEN }}
                KEYPAIR: ${{ secrets.KEYPAIR }}
                POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
                USER_GITHUB: ${{ secrets.USER_GITHUB }}
                VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}" > secret.txt
 
      - name: Upload kube config
        uses: actions/upload-artifact@v3
        with:
          name: secret.txt
          path: ./secret.txt
