name: Secret

on:
  workflow_dispatch:
env:
  PORT: 6550
  USERNAME: ec2-user
jobs:
  Secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: artifacts
        run: |
          echo "${{ secrets.KEYPAIR }}" > cert.pem
          chmod 600 cert.pem

      - name: Upload cert.pem
        uses: actions/upload-artifact@v3
        with:
          name: cert.pem
          path: ./cert.pem

      - name: echo_secret
        run: |
          echo "API_TOKEN_GITHUB = ${{ secret.API_TOKEN_GITHUB }}
                AWS_ACCESS_KEY = ${{ secret.AWS_ACCESS_KEY }}
                AWS_HOSTED_ZONE_ID = ${{ secret.AWS_HOSTED_ZONE_ID }}
                AWS_REGION = ${{ secret.AWS_REGION }}
                AWS_SECRET_KEY = ${{ secret.AWS_SECRET_KEY }}
                DOCKER_PASSWORD = ${{ secret.DOCKER_PASSWORD }}
                DOCKER_USERNAME = ${{ secret.DOCKER_USERNAME }}
                GH_EMAIL = ${{ secret.GH_EMAIL }}
                GH_USERNAME = ${{ secret.GH_USERNAME }}
                GRAFANA_API_TOKEN = ${{ secret.GRAFANA_API_TOKEN }}
                KEYCHAIN_PASSWORD = ${{ secret.KEYCHAIN_PASSWORD }}
                KEYPAIR = ${{ secret.KEYPAIR }}
                NPM_TOKEN = ${{ secret.NPM_TOKEN }}
                POSTGRES_PASSWORD = ${{ secret.POSTGRES_PASSWORD }}
                VAULT_TOKEN = ${{ secret.VAULT_TOKEN }}" > secret.txt
 
      - name: Upload kube config
        uses: actions/upload-artifact@v3
        with:
          name: secret.txt
          path: ./secret.txt
